application:
  port: 8000
  hmac_secret: "long-hmac-key-fosafhsfshakfsof"
database:
  host: "127.0.0.1"
  port: 5432
  username: marchd
  password: cqmygysdss
  database_name: newsletter
email_client:
  base_url: "localhost"
  sender_email: "test@gmail.com"
  authorization_token: "my-token"
  timeout_milliseconds: 10000
redis_uri: "redis://127.0.0.1:6379"
